language: python
os: linux
sudo: required
dist: trusty
python:
    - "3.6"
    - "3.8"
    - "3.11"
env:
    - IPERF_VERSION="3.0.6"
    - IPERF_VERSION="3.0.7"
    - IPERF_VERSION="3.0.8"
    - IPERF_VERSION="3.0.9"
    - IPERF_VERSION="3.0.10"
    - IPERF_VERSION="3.0.11"
    - IPERF_VERSION="3.0.12"
    - IPERF_VERSION="3.1"
    - IPERF_VERSION="3.1.1"
    - IPERF_VERSION="3.1.2"
    - IPERF_VERSION="3.1.3"
    - IPERF_VERSION="3.1.4"
    - IPERF_VERSION="3.1.5"
    - IPERF_VERSION="3.1.6"
    - IPERF_VERSION="3.1.7"
    - IPERF_VERSION="3.2"
    - IPERF_VERSION="3.3"
    - IPERF_VERSION="3.4"
    - IPERF_VERSION="3.5"
    - IPERF_VERSION="3.6"
before_install:
    # Download the various available iperf3 sources
    - if [[ "$IPERF_VERSION" == "3.0.6" ]]; then wget https://github.com/esnet/iperf/archive/3.0.6.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.0.7" ]]; then wget https://github.com/esnet/iperf/archive/3.0.7.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.0.8" ]]; then wget https://github.com/esnet/iperf/archive/3.0.8.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.0.9" ]]; then wget https://github.com/esnet/iperf/archive/3.0.9.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.0.10" ]]; then wget https://github.com/esnet/iperf/archive/3.0.10.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.0.11" ]]; then wget https://github.com/esnet/iperf/archive/3.0.11.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.0.12" ]]; then wget https://github.com/esnet/iperf/archive/3.0.12.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.1" ]]; then wget https://github.com/esnet/iperf/archive/3.1.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.1.1" ]]; then wget https://github.com/esnet/iperf/archive/3.1.1.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.1.2" ]]; then wget https://github.com/esnet/iperf/archive/3.1.2.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.1.3" ]]; then wget https://github.com/esnet/iperf/archive/3.1.3.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.1.4" ]]; then wget https://github.com/esnet/iperf/archive/3.1.4.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.1.5" ]]; then wget https://github.com/esnet/iperf/archive/3.1.5.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.1.6" ]]; then wget https://github.com/esnet/iperf/archive/3.1.6.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.1.7" ]]; then wget https://github.com/esnet/iperf/archive/3.1.7.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.2" ]]; then wget https://github.com/esnet/iperf/archive/3.2.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.3" ]]; then wget https://github.com/esnet/iperf/archive/3.3.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.4" ]]; then wget https://github.com/esnet/iperf/archive/3.4.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.5" ]]; then wget https://github.com/esnet/iperf/archive/3.5.tar.gz ;fi
    - if [[ "$IPERF_VERSION" == "3.6" ]]; then wget https://github.com/esnet/iperf/archive/3.6.tar.gz ;fi

    # Install iperf version selected above
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xvf *.tar.gz ;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd iperf-*/ ;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./bootstrap.sh ;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure && make && sudo make install ;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd .. ;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LD_LIBRARY_PATH=/usr/local/lib ;fi
install:
    - "pip install -r requirements.txt"
    - "pip install coverage"
    - "pip install coveralls"
script:
    - "coverage run --source=iperf3 setup.py test"
after_success: coveralls
